apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello
spec:
  entrypoint: main # the first template to run in the workflows
  templates:
    - name: main
      container: # this is a container template
        image: docker/whalesay # this image prints "hello world" to the console
        command: ["cowsay"]


